import { ItemKB, REFERENCIA_A_VALIDAR } from './types';

export const analiseKB: ItemKB[] = [
  {
    id: 'analise_conteudo',
    nome: 'Análise de conteúdo',
    categoria: 'analise',
    definicao_curta: 'Categorização sistemática do conteúdo de comunicações (falas, textos, documentos).',
    explicacao: 'Conjunto de técnicas para descrever objetivamente e sistematicamente o conteúdo de comunicações, geralmente por meio de categorias criadas a partir do material (ou de teoria prévia).',
    quando_usar: 'Quando se quer identificar padrões, frequências e categorias em dados textuais (entrevistas, documentos, respostas abertas).',
    exemplo: 'Categorizar respostas abertas de um questionário em temas recorrentes.',
    alertas: ['Dado que serve como insumo: respostas de entrevistas, questionários abertos ou documentos.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'analise_tematica',
    nome: 'Análise temática',
    categoria: 'analise',
    definicao_curta: 'Identificação, análise e relato de padrões (temas) em dados qualitativos.',
    explicacao: 'Processo flexível para identificar temas relevantes ao longo do conjunto de dados, geralmente qualitativos, ligados à pergunta de pesquisa.',
    quando_usar: 'Quando se busca identificar significados e padrões recorrentes em dados qualitativos, com certa flexibilidade teórica.',
    exemplo: 'Identificar temas centrais nas narrativas de entrevistas sobre uma experiência compartilhada.',
    alertas: [],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'analise_discurso',
    nome: 'Análise do discurso',
    categoria: 'analise',
    definicao_curta: 'Investiga como a linguagem constrói sentidos, relações de poder e posições dos sujeitos.',
    explicacao: 'Examina a linguagem em uso considerando seu contexto histórico, social e ideológico, para além do conteúdo manifesto.',
    quando_usar: 'Quando o interesse está em como algo é dito, as relações de poder e os efeitos de sentido da linguagem, não apenas no que é dito.',
    exemplo: 'Analisar como um discurso institucional constrói determinada identidade social.',
    alertas: ['Exige base teórica específica bem definida (há diferentes tradições de análise do discurso).'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'analise_documental_analise',
    nome: 'Análise documental (como método de análise)',
    categoria: 'analise',
    definicao_curta: 'Interpretação sistemática do conteúdo e contexto de produção de documentos.',
    explicacao: 'Vai além de reunir documentos: interpreta seu conteúdo à luz do contexto histórico e institucional de produção.',
    quando_usar: 'Quando os documentos coletados exigem interpretação contextualizada, não apenas categorização de conteúdo.',
    exemplo: 'Interpretar mudanças em políticas institucionais a partir de atas ao longo do tempo.',
    alertas: [],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'estatistica_descritiva',
    nome: 'Estatística descritiva',
    categoria: 'analise',
    definicao_curta: 'Organiza, resume e descreve dados quantitativos (médias, frequências, desvios).',
    explicacao: 'Conjunto de técnicas para sumarizar e apresentar dados quantitativos sem necessariamente testar hipóteses (médias, medianas, frequências, gráficos).',
    quando_usar: 'Para descrever o perfil de uma amostra ou as características gerais dos dados coletados.',
    exemplo: 'Calcular médias e desvios-padrão de notas em diferentes turmas.',
    alertas: [],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'estatistica_inferencial',
    nome: 'Estatística inferencial',
    categoria: 'analise',
    definicao_curta: 'Testa hipóteses e generaliza resultados de uma amostra para uma população.',
    explicacao: 'Utiliza testes estatísticos (t, ANOVA, regressão, qui-quadrado, etc.) para verificar se diferenças ou relações observadas na amostra são estatisticamente significativas.',
    quando_usar: 'Quando se quer testar hipóteses ou generalizar achados de uma amostra para a população de origem.',
    exemplo: 'Testar se a diferença de desempenho entre dois grupos é estatisticamente significativa.',
    alertas: ['Exige atenção aos pressupostos de cada teste estatístico.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'analise_qualitativa_interpretativa',
    nome: 'Análise qualitativa interpretativa',
    categoria: 'analise',
    definicao_curta: 'Interpretação aprofundada de sentidos e experiências a partir de referencial teórico específico.',
    explicacao: 'Abordagem interpretativa que busca compreender em profundidade os significados atribuídos pelos sujeitos, geralmente ancorada em um referencial teórico específico (ex.: fenomenologia, hermenêutica).',
    quando_usar: 'Quando a pesquisa está ancorada em uma tradição teórica interpretativa específica, além de categorização temática genérica.',
    exemplo: 'Interpretar relatos de experiência à luz de um referencial fenomenológico.',
    alertas: ['Explicitar claramente qual referencial teórico orienta a interpretação.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
];
