import { ItemKB, REFERENCIA_A_VALIDAR } from './types';

export const coletaKB: ItemKB[] = [
  {
    id: 'questionario_fechado',
    nome: 'Questionário (perguntas fechadas)',
    categoria: 'coleta',
    definicao_curta: 'Instrumento padronizado com respostas pré-definidas.',
    explicacao: 'Conjunto de perguntas com alternativas fixas de resposta, aplicado a vários respondentes de forma padronizada.',
    quando_usar: 'Quando se busca mensurar, comparar ou generalizar respostas em uma amostra maior.',
    exemplo: 'Escala de concordância (1 a 5) sobre satisfação com um serviço.',
    alertas: ['Vantagem: fácil de tabular. Limitação: pouco espaço para nuance ou significado subjetivo.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'questionario_aberto',
    nome: 'Questionário (perguntas abertas)',
    categoria: 'coleta',
    definicao_curta: 'Instrumento escrito com respostas livres.',
    explicacao: 'Perguntas que permitem ao respondente escrever livremente, sem alternativas pré-definidas.',
    quando_usar: 'Quando se deseja captar nuances na própria palavra do respondente, sem o custo logístico de uma entrevista.',
    exemplo: 'Pergunta aberta sobre motivações para escolha de curso.',
    alertas: ['Vantagem: mais riqueza que perguntas fechadas. Limitação: análise mais trabalhosa; taxa de resposta pode ser menor.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'entrevista_semiestruturada',
    nome: 'Entrevista semiestruturada',
    categoria: 'coleta',
    definicao_curta: 'Roteiro-guia com perguntas abertas, mas com espaço para aprofundamento.',
    explicacao: 'Combina um roteiro pré-definido de temas/perguntas com liberdade para o entrevistador explorar respostas em profundidade.',
    quando_usar: 'Quando se quer garantir cobertura de temas centrais, mas também abertura para o que emerge na fala do participante.',
    exemplo: 'Roteiro com 8 perguntas-guia sobre experiências docentes, com aprofundamento conforme as respostas.',
    alertas: ['Vantagem: equilíbrio entre profundidade e comparabilidade. Limitação: exige habilidade de condução.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'entrevista_aberta',
    nome: 'Entrevista aberta (não estruturada)',
    categoria: 'coleta',
    definicao_curta: 'Conversa guiada por um tema amplo, sem roteiro fixo de perguntas.',
    explicacao: 'O entrevistador parte de um tema geral e deixa a conversa fluir, com mínima interferência na direção do diálogo.',
    quando_usar: 'Quando se busca máxima profundidade e liberdade narrativa do participante, especialmente em temas pouco explorados.',
    exemplo: 'Convidar o participante a narrar livremente sua trajetória profissional.',
    alertas: ['Vantagem: profundidade e espontaneidade. Limitação: baixa comparabilidade entre entrevistas.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'grupo_focal',
    nome: 'Grupo focal',
    categoria: 'coleta',
    definicao_curta: 'Discussão em grupo mediada, sobre um tema definido.',
    explicacao: 'Reúne um pequeno grupo de participantes para discutir um tema, permitindo observar interações e consensos/divergências.',
    quando_usar: 'Quando o interesse inclui a interação entre participantes, não apenas respostas individuais.',
    exemplo: 'Discussão com 6 estudantes sobre percepções acerca de uma política institucional.',
    alertas: ['Exige moderação cuidadosa para evitar que vozes dominantes silenciem outras.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'observacao',
    nome: 'Observação (não participante)',
    categoria: 'coleta',
    definicao_curta: 'Registro sistemático de comportamentos/eventos sem intervenção do pesquisador.',
    explicacao: 'O pesquisador observa e registra o fenômeno sem interferir ou se envolver diretamente nele.',
    quando_usar: 'Quando se busca registrar comportamentos ou interações tal como ocorrem naturalmente.',
    exemplo: 'Observar e registrar padrões de interação em uma sala de espera.',
    alertas: [],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'observacao_participante',
    nome: 'Observação participante',
    categoria: 'coleta',
    definicao_curta: 'O pesquisador observa enquanto participa ativamente do contexto estudado.',
    explicacao: 'O pesquisador se insere no grupo ou contexto, participando das atividades enquanto observa e registra.',
    quando_usar: 'Quando a compreensão do fenômeno exige vivência direta do contexto pelo pesquisador.',
    exemplo: 'Participar das atividades de uma equipe de trabalho enquanto registra observações em diário de campo.',
    alertas: ['Exige reflexão explícita sobre o papel e a influência do pesquisador no campo.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'diario_campo',
    nome: 'Diário de campo',
    categoria: 'coleta',
    definicao_curta: 'Registro sistemático e contínuo de observações, impressões e reflexões do pesquisador.',
    explicacao: 'Instrumento de registro (geralmente escrito) usado ao longo de um período de observação ou intervenção em campo.',
    quando_usar: 'Como complemento a observação, observação participante, pesquisa-ação ou etnografia.',
    exemplo: 'Registros diários das interações observadas durante um estágio de pesquisa em uma instituição.',
    alertas: [],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'analise_documental_coleta',
    nome: 'Análise documental (como coleta)',
    categoria: 'coleta',
    definicao_curta: 'Levantamento sistemático de documentos como fonte de dados.',
    explicacao: 'Consiste em reunir documentos (oficiais, institucionais, pessoais, digitais) relevantes para a pesquisa.',
    quando_usar: 'Quando documentos existentes contêm informação relevante para responder à pergunta de pesquisa.',
    exemplo: 'Reunir relatórios anuais de uma organização ao longo de cinco anos.',
    alertas: ['Verificar autenticidade, autoria e contexto de produção dos documentos.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'registros_audiovisuais',
    nome: 'Registros audiovisuais',
    categoria: 'coleta',
    definicao_curta: 'Captação de imagem e/ou som como fonte de dados.',
    explicacao: 'Uso de fotografia, vídeo ou áudio para registrar o fenômeno estudado, permitindo análise posterior detalhada.',
    quando_usar: 'Quando aspectos visuais, gestuais ou sonoros do fenômeno são relevantes e difíceis de captar apenas por anotações.',
    exemplo: 'Gravar em vídeo interações em sala de aula para análise posterior.',
    alertas: ['Exige cuidados éticos redobrados quanto a consentimento e uso de imagem.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'escala',
    nome: 'Escalas psicométricas/padronizadas',
    categoria: 'coleta',
    definicao_curta: 'Instrumentos validados que mensuram construtos específicos.',
    explicacao: 'Instrumentos já testados e validados na literatura para medir construtos como ansiedade, satisfação, engajamento, etc.',
    quando_usar: 'Quando existe uma escala validada e adequada ao construto e à população da pesquisa.',
    exemplo: 'Aplicar uma escala validada de bem-estar subjetivo.',
    alertas: ['Verificar se a escala foi validada para a população/idioma/contexto da sua pesquisa.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'testes',
    nome: 'Testes (desempenho/conhecimento)',
    categoria: 'coleta',
    definicao_curta: 'Instrumentos que mensuram desempenho, habilidade ou conhecimento.',
    explicacao: 'Instrumentos padronizados para avaliar desempenho em uma tarefa, habilidade ou domínio de conteúdo.',
    quando_usar: 'Quando o objetivo envolve mensurar desempenho ou aprendizagem de forma comparável.',
    exemplo: 'Aplicar um teste de conhecimentos antes e depois de uma intervenção pedagógica.',
    alertas: [],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'bases_dados',
    nome: 'Bases de dados secundários',
    categoria: 'coleta',
    definicao_curta: 'Uso de dados já coletados por terceiros (institucionais, públicos, etc.).',
    explicacao: 'Utiliza dados previamente coletados e disponibilizados por outras instituições ou pesquisas, em vez de coleta direta.',
    quando_usar: 'Quando bases de dados existentes já contêm as informações necessárias para responder à pergunta de pesquisa.',
    exemplo: 'Utilizar microdados de um censo educacional público.',
    alertas: ['Verificar a documentação metodológica da base original e possíveis limitações de uso.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
];
