import { ItemKB, REFERENCIA_A_VALIDAR } from './types';

export const delineamentoKB: ItemKB[] = [
  {
    id: 'exploratoria',
    nome: 'Pesquisa exploratória',
    categoria: 'delineamento',
    definicao_curta: 'Proporciona maior familiaridade com um problema pouco estudado.',
    explicacao: 'Usada para construir hipóteses, refinar conceitos ou mapear um campo ainda pouco sistematizado.',
    quando_usar: 'Quando há pouca teoria ou pesquisa prévia consolidada sobre o tema.',
    exemplo: 'Mapear, por meio de entrevistas abertas, como um fenômeno emergente é percebido por especialistas.',
    alertas: ['Pode coexistir com outros delineamentos — não é mutuamente exclusiva.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'descritiva',
    nome: 'Pesquisa descritiva',
    categoria: 'delineamento',
    definicao_curta: 'Descreve características de uma população, fenômeno ou relação entre variáveis.',
    explicacao: 'Busca descrever "o que" ocorre, sem necessariamente explicar "por que".',
    quando_usar: 'Quando o objetivo é mapear, caracterizar ou descrever sistematicamente um fenômeno.',
    exemplo: 'Descrever o perfil socioeconômico de estudantes ingressantes em um curso.',
    alertas: [],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'explicativa',
    nome: 'Pesquisa explicativa',
    categoria: 'delineamento',
    definicao_curta: 'Busca identificar fatores que determinam ou contribuem para um fenômeno.',
    explicacao: 'Vai além da descrição, buscando relações de causa e efeito ou explicações para o fenômeno observado.',
    quando_usar: 'Quando já existe descrição suficiente do fenômeno e o interesse é entender seus determinantes.',
    exemplo: 'Investigar os fatores que explicam a evasão em cursos de graduação a distância.',
    alertas: ['Explicar causalidade em ciências sociais exige cautela metodológica adicional.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'estudo_caso',
    nome: 'Estudo de caso',
    categoria: 'delineamento',
    definicao_curta: 'Investigação profunda e contextualizada de um caso (pessoa, grupo, organização, evento).',
    explicacao: 'Permite compreender em profundidade um fenômeno dentro de seu contexto real, especialmente quando os limites entre fenômeno e contexto não são claros.',
    quando_usar: 'Quando o interesse é a profundidade e o contexto de um caso específico, não a generalização estatística.',
    exemplo: 'Estudar em profundidade como uma escola implementou um programa pedagógico específico.',
    alertas: ['Pode combinar múltiplas técnicas de coleta (entrevista, documentos, observação).'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'pesquisa_documental',
    nome: 'Pesquisa documental',
    categoria: 'delineamento',
    definicao_curta: 'Analisa documentos que ainda não receberam tratamento analítico.',
    explicacao: 'Utiliza fontes primárias como documentos oficiais, cartas, registros, mídias, ainda não analisadas cientificamente.',
    quando_usar: 'Quando a fonte principal de dados são documentos (não a literatura já publicada sobre o tema).',
    exemplo: 'Analisar atas de reuniões de um conselho escolar ao longo de dez anos.',
    alertas: ['Não confundir com pesquisa bibliográfica.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'pesquisa_bibliografica',
    nome: 'Pesquisa bibliográfica',
    categoria: 'delineamento',
    definicao_curta: 'Desenvolvida a partir de material já publicado (livros, artigos, etc.).',
    explicacao: 'Sistematiza e analisa a produção científica já existente sobre um tema, podendo constituir o delineamento principal (ex.: revisões) ou uma etapa de qualquer pesquisa.',
    quando_usar: 'Quando o objetivo central é mapear, sistematizar ou revisar a produção científica sobre um tema.',
    exemplo: 'Realizar uma revisão sistemática sobre métodos de ensino de programação.',
    alertas: [],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'pesquisa_acao',
    nome: 'Pesquisa-ação',
    categoria: 'delineamento',
    definicao_curta: 'O pesquisador intervém ativamente na realidade estudada, em cooperação com os participantes.',
    explicacao: 'Une pesquisa e ação prática: o pesquisador participa da resolução de um problema coletivo junto aos envolvidos, em ciclos de planejamento, ação e reflexão.',
    quando_usar: 'Quando há intenção explícita de transformar uma prática ou situação em conjunto com os participantes.',
    exemplo: 'Implementar e ajustar, junto a uma equipe escolar, uma nova estratégia pedagógica ao longo do semestre.',
    alertas: ['Exige atenção redobrada às questões éticas de intervenção.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'participante',
    nome: 'Pesquisa participante',
    categoria: 'delineamento',
    definicao_curta: 'O pesquisador se envolve com os sujeitos pesquisados como parte da investigação.',
    explicacao: 'Caracteriza-se pelo envolvimento direto do pesquisador com a comunidade ou grupo estudado, buscando uma compreensão a partir de dentro.',
    quando_usar: 'Quando o vínculo direto com o grupo pesquisado é condição para compreender o fenômeno.',
    exemplo: 'Participar das atividades de uma associação comunitária para compreender sua dinâmica organizativa.',
    alertas: [],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'etnografica',
    nome: 'Pesquisa etnográfica',
    categoria: 'delineamento',
    definicao_curta: 'Imersão prolongada em um contexto sociocultural para compreender seus significados e práticas.',
    explicacao: 'Utiliza observação (frequentemente participante) prolongada e diário de campo para compreender uma cultura ou grupo social a partir de sua própria lógica.',
    quando_usar: 'Quando o interesse é compreender práticas, significados e relações de um grupo em seu ambiente natural, ao longo do tempo.',
    exemplo: 'Observar, ao longo de um semestre, as rotinas e interações em uma sala de aula.',
    alertas: ['Costuma exigir tempo de campo mais longo que outros delineamentos.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'levantamento_survey',
    nome: 'Levantamento (survey)',
    categoria: 'delineamento',
    definicao_curta: 'Coleta dados de uma amostra representativa para inferir características de uma população.',
    explicacao: 'Aplica instrumentos padronizados (geralmente questionários) a uma amostra, buscando generalizar os achados para a população de origem.',
    quando_usar: 'Quando o objetivo é descrever ou mensurar características/opiniões de uma população a partir de uma amostra.',
    exemplo: 'Aplicar um questionário a uma amostra de estudantes para mapear hábitos de estudo.',
    alertas: ['A qualidade da amostragem é decisiva para a validade dos resultados.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'experimental',
    nome: 'Pesquisa experimental',
    categoria: 'delineamento',
    definicao_curta: 'Manipula deliberadamente uma variável independente, com controle de variáveis, para observar efeitos.',
    explicacao: 'Envolve grupos controlados (frequentemente com randomização) para testar relações de causa e efeito entre variáveis.',
    quando_usar: 'Quando é possível e ético manipular a variável independente e controlar variáveis intervenientes.',
    exemplo: 'Testar o efeito de dois métodos de ensino em grupos equivalentes, com pré e pós-teste.',
    alertas: ['Exige atenção rigorosa a questões éticas quando envolve pessoas.'],
    referencias: [REFERENCIA_A_VALIDAR],
  },
  {
    id: 'quase_experimental',
    nome: 'Pesquisa quase experimental',
    categoria: 'delineamento',
    definicao_curta: 'Manipula uma variável independente, mas sem randomização completa dos grupos.',
    explicacao: 'Semelhante ao experimento, mas os grupos já existem previamente (ex.: turmas já formadas), sem alocação aleatória dos participantes.',
    quando_usar: 'Quando a randomização não é viável ou ética, mas ainda é possível comparar grupos com e sem intervenção.',
    exemplo: 'Comparar o desempenho de duas turmas já existentes, uma submetida a uma nova metodologia e outra não.',
    alertas: [],
    referencias: [REFERENCIA_A_VALIDAR],
  },
];
